
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.VScale vscale1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vscale1 = new global::Gtk.VScale (null);
		this.vscale1.CanFocus = true;
		this.vscale1.Name = "vscale1";
		this.vscale1.Adjustment.Upper = 100;
		this.vscale1.Adjustment.PageIncrement = 10;
		this.vscale1.Adjustment.StepIncrement = 1;
		this.vscale1.Adjustment.Value = 10;
		this.vscale1.DrawValue = true;
		this.vscale1.Digits = 0;
		this.vscale1.ValuePos = ((global::Gtk.PositionType)(2));
		this.vbox1.Add (this.vscale1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vscale1]));
		w1.Position = 0;
		this.alignment1.Add (this.vbox1);
		this.Add (this.alignment1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Added += new global::Gtk.AddedHandler (this.OnAdded);
	}
}
